version: "3"
services:
  # fastapi-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fastapi-container-books
  #   restart: always
  #   ports:
  #     - "7070:7070"


  postgresql:
    container_name: books-postgresql
    image: postgres:alpine
    restart: always
    networks:
      postgres-net:
        aliases:
          - db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/data/postgres

networks:
  postgres-net:

volumes:
  postgres-data: