"""drop blocked

Revision ID: e59bc0b635a8
Revises: 
Create Date: 2024-01-06 15:50:43.399423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59bc0b635a8'
down_revision: Union[str, None] = 'cf23457a2c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
